# Import Library: Pandas

In [3]:
import pandas as pd 
# print the version 
print(pd.__version__)

3.0.6

# Datatype

### Series: 1 dimensional column of data

In [6]:
cars = pd.Series(["BMW", "TOYOTA", "MARCEDES"])
cars

0         BMW
1      TOYOTA
2    MARCEDES
dtype: str

In [7]:
colors = pd.Series(["Blue", "Red", "Pink"])
colors

0    Blue
1     Red
2    Pink
dtype: str

### Dataframe: row and column

In [9]:
car_data = pd.DataFrame({
    "Car type": cars,
    "Colors": colors
})
car_data

   Car type Colors
0       BMW   Blue
1    TOYOTA    Red
2  MARCEDES   Pink

In [12]:
Car_sales = pd.read_csv("../Pandas/Car_sales.csv")
Car_sales

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2
...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1

## Export data  (like if I changed something and I want to save it)

In [13]:
Car_sales.to_csv("../pandas/Car-sales-exported.csv")

## Describe Data

1- Exploring the data

In [15]:
# first check the data type for each column 
Car_sales.dtypes

Manufacturer               str
Model                      str
Sales_in_thousands     float64
__year_resale_value    float64
Vehicle_type               str
Price_in_thousands     float64
Engine_size            float64
Horsepower             float64
Wheelbase              float64
Width                  float64
dtype: object

In [17]:
# gives statistical overreveiw on numercal column (all numbers)
Car_sales.describe()

,Sales_in_thousands,__year_resale_value,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width
count,157.000000,121.000000,155.000000,156.000000,156.000000,156.000000,156.000000
mean,52.998076,18.072975,27.390755,3.060897,185.948718,107.487179,71.150000
std,68.029422,11.453384,14.351653,1.044653,56.700321,7.641303,3.451872
min,0.110000,5.160000,9.235000,1.000000,55.000000,92.600000,62.600000
25%,14.114000,11.260000,18.017500,2.300000,149.500000,103.000000,68.400000
50%,29.450000,14.180000,22.799000,3.000000,177.500000,107.000000,70.550000
75%,67.956000,19.875000,31.947500,3.575000,215.000000,112.200000,73.425000
max,540.561000,67.550000,85.500000,8.000000,450.000000,138.700000,79.900000

In [19]:
#info: show how many entries and columns I have, and nulls, and the datatype for each column (full overview) 
Car_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacturer         157 non-null    str
 1   Model                157 non-null    str
 2   Sales_in_thousands   157 non-null    float64
 3   __year_resale_value  121 non-null    float64
 4   Vehicle_type         157 non-null    str
 5   Price_in_thousands   155 non-null    float64
 6   Engine_size          156 non-null    float64
 7   Horsepower           156 non-null    float64
 8   Wheelbase            156 non-null    float64
 9   Width                156 non-null    float64
dtypes: float64(7), str(3)
memory usage: 12.4 KB

In [24]:
#doing mathematical fourms on the numeric data 
Car_sales.mean(numeric_only=True)

Sales_in_thousands      52.998076
__year_resale_value     18.072975
Price_in_thousands      27.390755
Engine_size              3.060897
Horsepower             185.948718
Wheelbase              107.487179
Width                   71.150000
dtype: float64

In [26]:
car_prices = pd.Series([10000, 3000, 77000])
car_prices.mean(numeric_only=True)

np.float64(30000.0)

In [27]:
Car_sales.sum(numeric_only=True)

Sales_in_thousands      8320.698
__year_resale_value     2186.830
Price_in_thousands      4245.567
Engine_size              477.500
Horsepower             29008.000
Wheelbase              16768.000
Width                  11099.400
dtype: float64

# Viewing and Selecting Data

In [33]:
Car_sales.head()  # it's ganna show the first 5 columns from up, or put specific number in ()

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2

In [36]:
Car_sales.tail()  # show the last 5 columns

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width
152,Volvo,V40,3.545,NaN,Passenger,24.4,1.9,160.0,100.5,67.6
153,Volvo,S70,15.245,NaN,Passenger,27.5,2.4,168.0,104.9,69.3
154,Volvo,V70,17.531,NaN,Passenger,28.8,2.4,168.0,104.9,69.3
155,Volvo,C70,3.493,NaN,Passenger,45.5,2.3,236.0,104.9,71.5
156,Volvo,S80,18.969,NaN,Passenger,36.0,2.9,201.0,109.9,72.1

In [ ]:
# .loc -> takes the index and it will bring the item
animals = pd.Series(["dog", "cat", "Hourse", "snake", " elephent"],
                    index = [44,55,22,11,33]) # this change the index number
animals

44          dog
55          cat
22       Hourse
11        snake
33     elephent
dtype: str

In [51]:
animals.loc[11]  # it based on the lebal that I costmized

'snake'

In [50]:
animals.iloc[3] # it works only with their real indecies not the costmized ones

'snake'

In [ ]:
Car_sales.loc[4]

Manufacturer                Audi
Model                         A4
Sales_in_thousands        20.397
__year_resale_value       22.255
Vehicle_type           Passenger
Price_in_thousands         23.99
Engine_size                  1.8
Horsepower                 150.0
Wheelbase                  102.6
Width                       68.2
Name: 4, dtype: object

In [ ]:
Car_sales["Horsepower"]

KeyError: '\tHorsepower'